(clear)
(load ontologia.clp)
(load reglas.clp)
(load prueba-10.clp)
(seed (integer (time))) 
(set-strategy random)
(watch focus) 
(reset)
(dribble-on ./salidas/salida-prueba-10.txt)
(run)
(dribble-off)