(clear)
(load ontologia.clp)
(load reglas.clp)
(load prueba-9.clp)
(seed (integer (time))) 
(set-strategy random)
(watch focus) 
(reset)
(dribble-on ./salidas/salida-prueba-9.txt)
(agenda)
(run 2)
(agenda)
(run)
(dribble-off)